name: lspapp
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  audio_session: ^0.1.10

  cloud_firestore: ^3.4.6
  curved_navigation_bar: ^1.0.3
  ffmpeg_kit_flutter_full: ^4.5.1
  file_picker: ^5.0.1
  firebase_auth: ^3.7.0
  firebase_core: ^1.21.1
  flutter:
    sdk: flutter
  #!
  flutter_sound: ^9.2.13
  get: ^4.6.5
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  google_speech: ^2.1.1
  http: ^0.13.3
  lottie: ^1.4.1
  permission_handler: ^10.0.0
  rxdart: ^0.27.5
  video_player: ^2.4.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sign/
